### ISSUE TITLE
Problem with the Tensorflow version

### ISSUE THREAD

**Issue by M-Ghorbel** [VisualComputingInstitute/triplet-reid#40]
Hello everybody,
I'm trying to run embed.py by following step by step the readme.txt but i'm always getting an error related to the tensorflow version, if i use tensorflow==0.12 i get this error
"  File "embed.py", line 153, in main
    dataset = tf.data.Dataset.from_tensor_slices(data_fids)
AttributeError: 'module' object has no attribute 'data' "
and i use tensorflow==1.5 i get this error
"AttributeError: 'str' object has no attribute 'get_shape' "
someone can help me please?

**Comment by Pandoro** [comment]
Using TensorFlow 0.12 is not supported since the dataset api which our code relies on wasn't introduced until 1.4. However, it should work with TensorFlow 1.5, at least we have successfully used it with later Tensorflow version. Could you post the complete error message, including lines from which the error originates from? Without it it's hard to guess where the error is coming from. Also please tell us if you are using our original code or you changed something. If I search for `get_shape` in our repository the only place where we use it directly is in the network definitions on input images. This should never be a string, so I'm a bit confused where this error should be coming from.

**Comment by M-Ghorbel** [comment]
![capture du 2018-06-11 11-54-16](https://user-images.githubusercontent.com/36449274/41227882-48abf0b4-6d6e-11e8-88c1-ad9cbffd0490.png)

**Comment by Pandoro** [comment]
So it seems like `tf_map_func` is trying to determine the shapes of outputs of the `common.fid_to_image` and at this point is getting a string object which obviously has no get_shape function. None of the return values are strings though. The first is an image and the last two should be string tensors not strings. However, I do see that @lucasb-eyer fixed an issues relating to this problem in a pull request #37  . Could it be you didn't check out a version after that PR was merged?

If that isn't the case I sadly don't have time to debug this for you right now. You should try to figure out which of the three return values is causing this issue and then figure out why this is a string in the first place, at this point it should all be tensors already.

**Comment by lucasb-eyer** [comment]
Alex is right, you are not using the latest master since `embed.py` line 244 doesn't correspond to what your error shows anymore. Please try again with the latest version of our code, it should work.

**Comment by M-Ghorbel** [comment]
where can i find the last version of the code please?
(sorry i'm new with these stuff)

**Comment by Pandoro** [comment]
If you checked out the code as a repository you should just git pull to get the latest changes. If you downloaded it as a zip file you will need to just re-download the master version from the main repo page.

**Comment by zishansami** [comment]
@M-Ghorbel 
Please replace line no. 157 in common.py with the following.
`return image_resized, fid, tf.convert_to_tensor(pid)`

This will solve the error for sure

**Comment by M-Ghorbel** [comment]
thank you for your help, since i used tensorflow 1.4 the error " "AttributeError: 'str' object has no attribute 'get_shape' " has disappeared but i'm getting another error "ValueError: Can't load save_path when it is None."

![capture du 2018-06-13 09-48-21](https://user-images.githubusercontent.com/36449274/41340343-05600282-6eef-11e8-94e8-11538df0c59a.png)

**Comment by zishansami** [comment]
If you have not trained earlier using this script..
You need to provide a trained model checkpoint using --checkpoint argument.
You can find that in the [Tf-release section](https://github.com/VisualComputingInstitute/triplet-reid/releases/tag/250eb1).

They also did not provide args.json file in the earlier release. You need that to run the trained model. I do not know whether they have updated in the release or not. 
If not, check earlier issue i created for the same.

**Comment by lucasb-eyer** [comment]
@zishansami is right, and we indeed didn't get around to updating the release with the args.json file yet.

**Comment by M-Ghorbel** [comment]
@zishansami 
after downloading the zip, i get three files, where should i copy them?

**Comment by zishansami102** [comment]
In the experiment folder of course. 
And give the path relative to the experiment folder with --checkpoint

**Comment by M-Ghorbel** [comment]
@zishansami 
![capture du 2018-06-14 09-20-22](https://user-images.githubusercontent.com/36449274/41400148-3433d334-6fb4-11e8-9c4a-4fd7a9b40a03.png)


![capture du 2018-06-14 09-19-27](https://user-images.githubusercontent.com/36449274/41400101-10ebddfe-6fb4-11e8-92c7-ceec6915d314.png)

OSError: Unable to create file (unable to open file: name = '/test_embeddings.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 242)

**Comment by zishansami102** [comment]
Run this.
python3 embed.py \
--experiment_root ~/experiments/my_experiment \
--dataset querynameno.csv \
--filename test_embeddings.h5 \
--checkpoint checkpoint-25000

If still throws the same error..
then there is problem with your h5py.
Try updating it

**Comment by lucasb-eyer** [comment]
A path starting with a `/` is an absolute path, not a relative one. It complains that it can't create the file `/test_embeddings.h5`, obviously because it's in the root folder.

**Comment by M-Ghorbel** [comment]
@zishansami 
it still not working, i'm getting another error, i don't know why it's so complicated, i did follow your instructions but still have problems.
![capture du 2018-06-19 10-09-22](https://user-images.githubusercontent.com/36449274/41588281-3d1f43ea-73a9-11e8-8424-e4525e4491d6.png)

**Comment by Pandoro** [comment]
Please actually read the error messages before blindly posting them. Just looking at them it should be obvious what is wrong.

**Comment by lucasb-eyer** [comment]
I'm going to close this issue as the original issue has long been solved. For other problems, please open new issues about these specific problems, but as @Pandoro said, please read the error messages carefully and try at least a little to solve them before posting.
